apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  MYSQL_ROOT_PASSWORD: "redhat"
  MYSQL_DATABASE: "studentapp"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "redhat"
  MYSQL_HOST: "localhost"