apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: my-ds
  namespace: ops
  labels:
    app: my-app

spec:
  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app

    spec:
      nodeSelector:
        kubernetes.io/arch: amd64

      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP