apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: mariadb-pod
spec:
  containers:
    - name: mariadb
      image: mariadb:latest
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_ROOT_PASSWORD