---
apiVersion: v1
kind: Namespace
metadata:
  name: ops

...


---
apiVersion: v1
kind: Pod
metadata:
  namespace: ops
  name: my-app
  labels:
    app: my-app

spec:
  containers:
    - name: my-app
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP

    - name: backend
      image: tomcat:latest
      ports:
        - name: java
          containerPort: 8080
          protocol: TCP

...

---
kind: Service
apiVersion: v1
metadata:
  name:  my-svc
  namespace: ops    
spec:
  selector:
    app:  my-app
  ports:
  - port:  80
    targetPort:  8080

... 