apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-app
  labels:
    app: my-app

spec:
  containers:
    - name: my-app
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP

    - name: backend
      image: tomcat:latest
      ports:
        - name: java
          containerPort: 8080
          protocol: TCP