apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
  labels:
    app: my-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: mariadb:latest
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "redhat"
  selector:
    matchLabels:
      app: my-app
